source:      .
destination: ./_site
plugins_dir: ./_plugins
exclude: [bin, CNAME, Gemfile, Gemfile.lock, README.md]
permalink: /:title
markdown: kramdown
url: http://clojuremqtt.info/

kramdown:
    input:          GFM
    hard_wrap:      false
